### ISSUE TITLE
[공통] 스크롤 바 존재 여부에 따른 헤더 영역 흔들림 이슈

### ISSUE THREAD

**Issue by yujleee** [Team-Detto/Detto#137]
## 개요 🔎

스크롤 바가 있는 영역, 없는 영역에 따라서 헤더가 덜컹거리는 이슈가 있습니다.

## 작업사항 📝

- [ ] 헤더 덜컹거림 이슈 해결

**Comment by yujleee** [comment]
`scrollbar-gutter` 라는 속성을 이용할 수 있을까 했는데 `html` `body` 에는 적용이 안되네요 ㅠㅠ  다른 페이지들을 확인해보니 원래 이런 것 같기도... 🤔

**Comment by su-no** [comment]
body에 overflow-y: overlay 를 적용하면 되는데,,,,,,,, 문제는 그러면 window.scroll이 안되네요 😓 저도 다시 찾아볼게요!
